global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'hft-fast-path'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    scrape_interval: 1s
